// Your Messier catalogue data.
// Edit an entry as you finish a target: set photographed to true,
// point "image" at a file in the images/ folder, and fill in the rest.
const MESSIER_DATA = [
  {
    "id": 1,
    "catalog": "M1",
    "commonName": "Crab Nebula",
    "type": "Supernova remnant",
    "constellation": "Taurus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 2,
    "catalog": "M2",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Aquarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 3,
    "catalog": "M3",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Canes Venatici",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 4,
    "catalog": "M4",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Scorpius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 5,
    "catalog": "M5",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Serpens",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 6,
    "catalog": "M6",
    "commonName": "Butterfly Cluster",
    "type": "Open cluster",
    "constellation": "Scorpius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 7,
    "catalog": "M7",
    "commonName": "Ptolemy Cluster",
    "type": "Open cluster",
    "constellation": "Scorpius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 8,
    "catalog": "M8",
    "commonName": "Lagoon Nebula",
    "type": "Emission nebula",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 9,
    "catalog": "M9",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 10,
    "catalog": "M10",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 11,
    "catalog": "M11",
    "commonName": "Wild Duck Cluster",
    "type": "Open cluster",
    "constellation": "Scutum",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 12,
    "catalog": "M12",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 13,
    "catalog": "M13",
    "commonName": "Hercules Cluster",
    "type": "Globular cluster",
    "constellation": "Hercules",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 14,
    "catalog": "M14",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 15,
    "catalog": "M15",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Pegasus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 16,
    "catalog": "M16",
    "commonName": "Eagle Nebula",
    "type": "Emission nebula / cluster",
    "constellation": "Serpens",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 17,
    "catalog": "M17",
    "commonName": "Omega Nebula",
    "type": "Emission nebula",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 18,
    "catalog": "M18",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 19,
    "catalog": "M19",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 20,
    "catalog": "M20",
    "commonName": "Trifid Nebula",
    "type": "Emission / reflection nebula",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 21,
    "catalog": "M21",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 22,
    "catalog": "M22",
    "commonName": "Sagittarius Cluster",
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 23,
    "catalog": "M23",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 24,
    "catalog": "M24",
    "commonName": "Sagittarius Star Cloud",
    "type": "Star cloud",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 25,
    "catalog": "M25",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 26,
    "catalog": "M26",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Scutum",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 27,
    "catalog": "M27",
    "commonName": "Dumbbell Nebula",
    "type": "Planetary nebula",
    "constellation": "Vulpecula",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 28,
    "catalog": "M28",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 29,
    "catalog": "M29",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Cygnus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 30,
    "catalog": "M30",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Capricornus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 31,
    "catalog": "M31",
    "commonName": "Andromeda Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Andromeda",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 32,
    "catalog": "M32",
    "commonName": null,
    "type": "Dwarf elliptical galaxy",
    "constellation": "Andromeda",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 33,
    "catalog": "M33",
    "commonName": "Triangulum Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Triangulum",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 34,
    "catalog": "M34",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Perseus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 35,
    "catalog": "M35",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Gemini",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 36,
    "catalog": "M36",
    "commonName": "Pinwheel Cluster",
    "type": "Open cluster",
    "constellation": "Auriga",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 37,
    "catalog": "M37",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Auriga",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 38,
    "catalog": "M38",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Auriga",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 39,
    "catalog": "M39",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Cygnus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 40,
    "catalog": "M40",
    "commonName": "Winnecke 4",
    "type": "Double star",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 41,
    "catalog": "M41",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Canis Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 42,
    "catalog": "M42",
    "commonName": "Orion Nebula",
    "type": "Emission nebula",
    "constellation": "Orion",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 43,
    "catalog": "M43",
    "commonName": "De Mairan's Nebula",
    "type": "Emission nebula",
    "constellation": "Orion",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 44,
    "catalog": "M44",
    "commonName": "Beehive Cluster",
    "type": "Open cluster",
    "constellation": "Cancer",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 45,
    "catalog": "M45",
    "commonName": "Pleiades",
    "type": "Open cluster",
    "constellation": "Taurus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 46,
    "catalog": "M46",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Puppis",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 47,
    "catalog": "M47",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Puppis",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 48,
    "catalog": "M48",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Hydra",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 49,
    "catalog": "M49",
    "commonName": null,
    "type": "Elliptical galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 50,
    "catalog": "M50",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Monoceros",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 51,
    "catalog": "M51",
    "commonName": "Whirlpool Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Canes Venatici",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 52,
    "catalog": "M52",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Cassiopeia",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 53,
    "catalog": "M53",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 54,
    "catalog": "M54",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 55,
    "catalog": "M55",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 56,
    "catalog": "M56",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Lyra",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 57,
    "catalog": "M57",
    "commonName": "Ring Nebula",
    "type": "Planetary nebula",
    "constellation": "Lyra",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 58,
    "catalog": "M58",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 59,
    "catalog": "M59",
    "commonName": null,
    "type": "Elliptical galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 60,
    "catalog": "M60",
    "commonName": null,
    "type": "Elliptical galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 61,
    "catalog": "M61",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 62,
    "catalog": "M62",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 63,
    "catalog": "M63",
    "commonName": "Sunflower Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Canes Venatici",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 64,
    "catalog": "M64",
    "commonName": "Black Eye Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 65,
    "catalog": "M65",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Leo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 66,
    "catalog": "M66",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Leo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 67,
    "catalog": "M67",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Cancer",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 68,
    "catalog": "M68",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Hydra",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 69,
    "catalog": "M69",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 70,
    "catalog": "M70",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 71,
    "catalog": "M71",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagitta",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 72,
    "catalog": "M72",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Aquarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 73,
    "catalog": "M73",
    "commonName": null,
    "type": "Asterism",
    "constellation": "Aquarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 74,
    "catalog": "M74",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Pisces",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 75,
    "catalog": "M75",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Sagittarius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 76,
    "catalog": "M76",
    "commonName": "Little Dumbbell Nebula",
    "type": "Planetary nebula",
    "constellation": "Perseus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 77,
    "catalog": "M77",
    "commonName": null,
    "type": "Spiral galaxy (Seyfert)",
    "constellation": "Cetus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 78,
    "catalog": "M78",
    "commonName": null,
    "type": "Reflection nebula",
    "constellation": "Orion",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 79,
    "catalog": "M79",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Lepus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 80,
    "catalog": "M80",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Scorpius",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 81,
    "catalog": "M81",
    "commonName": "Bode's Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 82,
    "catalog": "M82",
    "commonName": "Cigar Galaxy",
    "type": "Starburst galaxy",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 83,
    "catalog": "M83",
    "commonName": "Southern Pinwheel Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Hydra",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 84,
    "catalog": "M84",
    "commonName": null,
    "type": "Lenticular galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 85,
    "catalog": "M85",
    "commonName": null,
    "type": "Lenticular galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 86,
    "catalog": "M86",
    "commonName": null,
    "type": "Lenticular galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 87,
    "catalog": "M87",
    "commonName": "Virgo A",
    "type": "Elliptical galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 88,
    "catalog": "M88",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 89,
    "catalog": "M89",
    "commonName": null,
    "type": "Elliptical galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 90,
    "catalog": "M90",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 91,
    "catalog": "M91",
    "commonName": null,
    "type": "Barred spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 92,
    "catalog": "M92",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Hercules",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 93,
    "catalog": "M93",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Puppis",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 94,
    "catalog": "M94",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Canes Venatici",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 95,
    "catalog": "M95",
    "commonName": null,
    "type": "Barred spiral galaxy",
    "constellation": "Leo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 96,
    "catalog": "M96",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Leo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 97,
    "catalog": "M97",
    "commonName": "Owl Nebula",
    "type": "Planetary nebula",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 98,
    "catalog": "M98",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 99,
    "catalog": "M99",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 100,
    "catalog": "M100",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Coma Berenices",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 101,
    "catalog": "M101",
    "commonName": "Pinwheel Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 102,
    "catalog": "M102",
    "commonName": "Spindle Galaxy",
    "type": "Lenticular galaxy",
    "constellation": "Draco",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 103,
    "catalog": "M103",
    "commonName": null,
    "type": "Open cluster",
    "constellation": "Cassiopeia",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 104,
    "catalog": "M104",
    "commonName": "Sombrero Galaxy",
    "type": "Spiral galaxy",
    "constellation": "Virgo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 105,
    "catalog": "M105",
    "commonName": null,
    "type": "Elliptical galaxy",
    "constellation": "Leo",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 106,
    "catalog": "M106",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Canes Venatici",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 107,
    "catalog": "M107",
    "commonName": null,
    "type": "Globular cluster",
    "constellation": "Ophiuchus",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 108,
    "catalog": "M108",
    "commonName": null,
    "type": "Spiral galaxy",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 109,
    "catalog": "M109",
    "commonName": null,
    "type": "Barred spiral galaxy",
    "constellation": "Ursa Major",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  },
  {
    "id": 110,
    "catalog": "M110",
    "commonName": null,
    "type": "Dwarf elliptical galaxy",
    "constellation": "Andromeda",
    "photographed": false,
    "image": null,
    "datePhotographed": null,
    "equipment": null,
    "exposure": null,
    "notes": null
  }
];
